configurationVariables:
  globalvariable.JcHelloWorldAPI.greeting.value: Hello
info:
  model: int-scaffold
packages:
- gitBranch: release/1.0.0
  gitServerName: johnpcarter
  gitUrl: https://github.com/johnpcarter
  gitUsername: johnpcarter
  name: JC_STELLANTIS_DEMOProject
- gitBranch: v1.0.0
  gitServerName: johnpcarter
  gitUrl: https://github.com/johnpcarter
  gitUsername: johnpcarter
  name: JcHelloWorldAPI
version: 1.0.0
